// tutoriel nuit (nightwatch) http://nightwatchjs.org/api
// comando para executar: em frontend, node_modules\.bin\nightwatch
// caso não funcione executar npm install, caso ainda não funcione assista ao video
module.exports = {
  'test': function (browser) {
    browser
      .url('http://localhost:8081/#/CadastrarUsuario')
      .waitForElementVisible('body', 3000)
      .setValue('input[id=name]', 'wesley').pause(500)
      .setValue('input[id=lastName]', 'silva').pause(500)
      .setValue('input[id=email]', 'teste@email.com').pause(500)
      .setValue('input[id=salary]', '1000').pause(500)
      .setValue('input[id=pis]', '12345678912').pause(500)
      .setValue('input[id=workload]', '8').pause(500)
      .setValue('input[id=phoneNumber1]', '123456789').pause(500)
      .setValue('input[id=phoneNumber2]', '987654321').pause(500)
      .setValue('input[id=supervisor]', 'Zeller').pause(500)
      .setValue('input[id=joiningDate]', '2018-01-01').pause(500)
      .setValue('input[id=hourType]', '1').pause(500)
      .setValue('input[id=password]', '123456789').pause(500)
      .setValue('input[id=passwordValidator]', '123456789').pause(1000)
      .click('button[id=submit]').pause(5000)
      // .url('http://localhost:8081/#/CadastrarEmpresa')
      // .waitForElementVisible('body', 3000)
      // .setValue('input[id=socialName]', 'test1')
      // .url('http://localhost:8081/#/LinhaDoTempo')
      // .pause(500)
      // .setValue('input[id=tradingName]', 'test2')
      // .pause(500)
      // .setValue('input[id=cnpj]', '61442737000230')
      // .pause(500)
      // .setValue('input[id=stateRegistration]', '454504330118')
      // .pause(500)
      // .setValue('input[id=zipCode]', '08750710')
      // .pause(500)
      // .setValue('input[id=number]', '123')
      // .pause(500)
      // .setValue('input[id=street]', 'Rua teste')
      // .pause(500)
      // .setValue('input[id=city]', 'Mogi das cruzes')
      // .pause(500)
      // .setValue('input[id=state]', 'SP')
      // .pause(500)
      // .click('button[id=success]')
      // .pause(2000)
      // .verify.containsText('#main', 'Dados da Empresa')
      // .pause(5000)
      .end()
  }
}
